### PR TITLE
A few notes for the FAQ

### PR DESCRIPTION
**Pull request by pfrazee**
Wanted to add notes and corrections, felt like the easiest solution was to fork and do some edits. Not really mergeable because some of my notes are just thoughts I've dumped in there.

I didn't hit the entire FAQ but at least 66%

### CODE REVIEW

**Comment by urbien** [comment]
Hm, I am not sure I understand the followin
> Key rotation/replacement is one of the motivations for introducing DNS to Hyper's addressing scheme as it would enable key rotation via the indirection of name lookup.

I discussed key rotation for individual Hypercores with @mafintosh and multi-key module came up as the solution. Not sure how DNS could help and why would we use DNS which is quite centralized and hard to update. Didn't we git rid of it with DHT?

**Comment by urbien** [comment]
can you elaborate on the manifest

**Comment by pfrazee** [comment]
> I discussed key rotation for individual Hypercores with @mafintosh and multi-key module came up as the solution. Not sure how DNS could help and why would we use DNS which is quite centralized and hard to update. Didn't we git rid of it with DHT?

Well, people still want shortnames. We've discussed some alternatives to the ICANN DNS but I think any alternatives would have to be additions, not replacements.

I'm not sure if DHT == DNS is quite the right way to describe it. I often think of it more as a replacement for IP addresses.

I wouldn't propose DNS as the only solution to key rotation, but it's obviously able to accomplish that task.

> can you elaborate on the manifest

Nothing thought-out, just suggesting a userland application, eg a package manager, could have manifests which record the strong-link hashes.

**Review by urbien — COMMENTED** [review]
this is good to know that Hyperspace provides additional protections. I was thinking about the library-style use of Hypercore. In a serverless environment there is no long running processes / daemons like Hyperspace. The VM is launched on-event and is destroyed in 200ms or so. The side effect is multiple VMs may launch simultaneously when multiple evens occur. They all might be reading / writing simultaneously from the Hypercore. I suppose we will need to guard against simultaneous writes, but must allow simultaneous reads.

**Comment by urbien** [comment]
on Key rotation, I see that we are discussing 2 separate things. I think you are talking about human readable URLs, as in the discovery key to the Hyperdrive in the swarm. And I agree, people will need short names that can be remembered and searched well. For me DNS has 2 dimensions:

- mapping a location independent string to a location (IP address). AWS URLs are not short as they have a very long host name part in them. They provide this independence of the actual IP address which decouples network infrastructure from services. DHT does that in a decentralized manner (except the bootstrap IPs)
- reserving a user-friendly recognizable name. This we do today with the registrar. This part is very to decentralize https://en.wikipedia.org/wiki/Zooko%27s_triangle. DHT does not help here. Namecoin was first to solve Zooko triangle puzzle, and Ethereum [ENS smart contract](https://decrypt.co/resources/ethereum-name-service-ens-explained-guide-learn
) is now well on the way to be adopted as as decentralized solution for this. I spent quite some time discussing this subject in 2014 with various people who were trying to solve it, e.g. with Greg who created [okTurtles](https://github.com/okTurtles/dnschain) and with the Blockstack guys.

When I talked about key rotation though, I meant another problem:
There is a need for changing private key of existing Hypercore. It is needed when you restore on a new device, for moving to a new key when old key is lost or suspected to be compromised, and for security best practices, as keys should change (get rotated) over time. We need to solve this for mass deployment. We all are familiar with Gmail mechanisms for recovery of lost credentials. They are plentiful and are being extended with more options every year. As a first step, I was thinking how to use multi-key to continue with the same Hypercore but new credentials.

**Review by urbien — COMMENTED** [review]
Did i get it right? Strong link is adding a signed hash of the Merkle tree at a particular position (seq) in the log?

**Comment by urbien** [comment]
I seem to have merged all suggestions above and added a more content to FAQ, e.g. USP 'time travel', 'real-time UI updates', more use cases for hyperbee as streaming DB. 
Closing this PR.

**Pull request closed without merging**
